In [2]:
import numpy
import pandas as pd
from pathlib import Path 
import torch

import matplotlib.pyplot as plt

In [3]:
parent_dir = Path("anphy_sleep_data") 
parent_dir = parent_dir.joinpath("patient_records")
raw_dir = parent_dir.joinpath("raw")
clean_dir = parent_dir.joinpath("clean")

In [4]:
data = torch.load(clean_dir / f"EPCTL01_dataset.pt",  weights_only=False)
X = data["X"]
y = data["y"]

In [7]:
df = pd.DataFrame(X[0, :, :].T)
df

,0,1,2,3,4,5,6,7,8,9,...,83,84,85,86,87,88,89,90,91,92
0,-0.000003,0.000005,6.257800e-07,0.000017,0.000014,-0.000023,0.000027,0.000018,0.000026,0.000009,...,-273.960890,-3190.463844,1783.477768,102.319988,-93.893639,74.248955,1.126530,0.001235,0.000018,0.000011
1,-0.000007,0.000004,-2.338649e-06,0.000017,0.000011,-0.000020,0.000025,0.000023,0.000022,0.000010,...,-228.799374,-3209.017870,993.288425,98.812013,-102.043952,-64.183552,-8.072688,0.000513,0.000006,0.000003
2,-0.000007,0.000008,-5.962635e-06,0.000022,0.000008,-0.000016,0.000024,0.000027,0.000022,0.000014,...,-125.166332,-3191.308093,349.313744,104.505197,-100.952536,-85.057466,-3.997801,-0.000113,0.000009,-0.000002
3,-0.000011,0.000006,-3.505274e-06,0.000018,0.000010,-0.000019,0.000024,0.000027,0.000022,0.000015,...,-118.022011,-3208.310351,460.058583,101.695453,-110.727497,-56.282808,1.673310,-0.000042,0.000016,-0.000004
4,-0.000012,0.000004,-6.161396e-06,0.000020,0.000009,-0.000017,0.000021,0.000026,0.000019,0.000013,...,-116.980039,-3191.884717,509.082421,99.512227,-112.251240,-55.015660,8.533433,0.000013,0.000025,-0.000004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.000024,0.000039,1.720548e-05,0.000015,0.000017,-0.000027,0.000025,0.000015,0.000022,0.000017,...,-100.678915,-216.621812,-79.559531,-25.963820,-32.719229,-22.072702,2.405039,-0.000043,0.000009,0.000013
2996,0.000027,0.000040,1.511972e-05,0.000015,0.000020,-0.000029,0.000031,0.000015,0.000030,0.000018,...,-107.972203,-222.761693,-88.421961,-22.822340,-29.251507,-20.772691,3.295690,-0.000051,0.000011,0.000016
2997,0.000027,0.000040,1.324979e-05,0.000012,0.000019,-0.000028,0.000032,0.000018,0.000035,0.000021,...,-104.759225,-219.694547,-78.899677,-22.682409,-29.856973,-19.330047,5.252131,-0.000040,0.000011,0.000018
2998,0.000021,0.000039,1.344853e-05,0.000013,0.000017,-0.000026,0.000031,0.000024,0.000033,0.000030,...,-97.155431,-222.569641,-98.449648,-23.748305,-32.897216,-21.154227,5.763595,-0.000059,0.000011,0.000015
2999,0.000025,0.000043,1.508221e-05,0.000017,0.000018,-0.000027,0.000032,0.000020,0.000032,0.000026,...,-99.622027,-220.446408,-106.758941,-20.575668,-31.650730,-25.871366,4.888818,-0.000068,0.000011,0.000016

In [8]:
df.corr()

,0,1,2,3,4,5,6,7,8,9,...,83,84,85,86,87,88,89,90,91,92
0,1.000000,0.717461,0.579619,0.454167,0.243162,-0.263446,0.228193,0.189140,0.304451,0.275805,...,0.015275,0.090695,0.004009,-0.029839,-0.094911,0.109422,-0.004295,0.019615,-0.034829,0.198241
1,0.717461,1.000000,0.061406,0.739257,-0.271974,0.214427,-0.109953,0.036960,-0.034398,0.022802,...,0.021575,-0.129623,-0.005951,0.417672,-0.509989,-0.020099,0.047169,-0.004294,0.009522,-0.288052
2,0.579619,0.061406,1.000000,-0.062161,0.742483,-0.705965,0.486118,0.193222,0.451010,0.356158,...,-0.069329,0.199964,0.017798,-0.595228,0.574963,0.180632,-0.031309,0.036874,-0.013811,0.678083
3,0.454167,0.739257,-0.062161,1.000000,-0.261691,0.239637,-0.122959,0.099550,-0.097123,-0.056353,...,-0.103298,-0.087649,-0.004685,0.734787,-0.695101,-0.065981,0.095150,-0.026091,0.128957,-0.382834
4,0.243162,-0.271974,0.742483,-0.261691,1.000000,-0.968258,0.848820,0.484677,0.656421,0.504606,...,-0.333682,0.256238,0.029192,-0.576456,0.523120,0.141430,0.034690,0.050342,0.070563,0.880019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,0.109422,-0.020099,0.180632,-0.065981,0.141430,-0.075843,0.165665,0.123128,0.199082,0.306171,...,-0.248669,0.270805,0.668952,-0.128983,0.204073,1.000000,0.082053,0.684978,0.059921,0.270626
89,-0.004295,0.047169,-0.031309,0.095150,0.034690,-0.033112,0.113288,0.132225,0.149100,0.096577,...,-0.050651,0.126749,0.090787,0.061069,-0.024505,0.082053,1.000000,0.040448,0.970857,0.063097
90,0.019615,-0.004294,0.036874,-0.026091,0.050342,-0.025691,0.082113,0.063081,0.107717,0.135444,...,-0.637729,0.251388,0.984969,-0.041092,0.026920,0.684978,0.040448,1.000000,0.029136,0.093847
91,-0.034829,0.009522,-0.013811,0.128957,0.070563,-0.077971,0.119789,0.135938,0.129465,0.063287,...,-0.095972,0.090758,0.086168,0.097582,-0.046173,0.059921,0.970857,0.029136,1.000000,0.060242
92,0.198241,-0.288052,0.678083,-0.382834,0.880019,-0.838292,0.849433,0.467134,0.780831,0.624067,...,-0.153966,0.241570,0.071500,-0.625734,0.645465,0.270626,0.063097,0.093847,0.060242,1.000000

In [9]:
y

array([1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 3, 3, 1, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 3, 3, 2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 4, 4, 4, 3,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 3,
       3, 4, 4, 4, 4, 4, 3, 3, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4,
       3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2,
       2, 2, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 5, 5, 5, 5, 2,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 3, 4, 4, 4, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 4, 4, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 1, 2, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 3, 3, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0])